-- Insert approved deals for testing the Available Deals page
-- These deals will appear in the admin dashboard as approved deals

INSERT INTO deals (
    id,
    name,
    location,
    city,
    area,
    bedrooms,
    bedroom_count,
    size,
    listed_price,
    price_value,
    estimate_min,
    estimate_max,
    estimate_range,
    discount,
    rental_yield,
    building_status,
    status,
    active,
    batch_date,
    approved_at,
    created_at,
    updated_at
) VALUES
-- Deal 1: Active Approved Deal
(
    gen_random_uuid(),
    'Marina Pinnacle Tower',
    'Dubai Marina',
    'dubai',
    'marina',
    '1BR',
    '1',
    '750 sq ft',
    'AED 1,450,000',
    1450000,
    1750000,
    1820000,
    'AED 1,750,000 - 1,820,000',
    '18.2%',
    '6.8%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),
-- Deal 2: Active Approved Deal
(
    gen_random_uuid(),
    'Downtown Burj Vista',
    'Downtown Dubai',
    'dubai',
    'downtown',
    '2BR',
    '2',
    '1,100 sq ft',
    'AED 2,850,000',
    2850000,
    3450000,
    3580000,
    'AED 3,450,000 - 3,580,000',
    '19.1%',
    '5.9%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '3 days',
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    CURRENT_TIMESTAMP - INTERVAL '3 days',
    CURRENT_TIMESTAMP - INTERVAL '2 days'
),
-- Deal 3: Active Approved Deal
(
    gen_random_uuid(),
    'Business Bay Executive',
    'Business Bay',
    'dubai',
    'business-bay',
    'Studio',
    'studio',
    '580 sq ft',
    'AED 895,000',
    895000,
    1080000,
    1125000,
    'AED 1,080,000 - 1,125,000',
    '17.8%',
    '7.2%',
    'OFF_PLAN',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '4 days',
    CURRENT_TIMESTAMP - INTERVAL '3 days',
    CURRENT_TIMESTAMP - INTERVAL '4 days',
    CURRENT_TIMESTAMP - INTERVAL '3 days'
),
-- Deal 4: Active Approved Deal
(
    gen_random_uuid(),
    'Jumeirah Beach Residence',
    'JBR',
    'dubai',
    'jumeirah',
    '2BR',
    '2',
    '1,250 sq ft',
    'AED 3,250,000',
    3250000,
    3950000,
    4100000,
    'AED 3,950,000 - 4,100,000',
    '18.9%',
    '6.1%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    CURRENT_TIMESTAMP - INTERVAL '4 days',
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    CURRENT_TIMESTAMP - INTERVAL '4 days'
),
-- Deal 5: Active Approved Deal
(
    gen_random_uuid(),
    'DIFC Financial Plaza',
    'DIFC',
    'dubai',
    'downtown',
    '1BR',
    '1',
    '850 sq ft',
    'AED 1,750,000',
    1750000,
    2120000,
    2200000,
    'AED 2,120,000 - 2,200,000',
    '18.4%',
    '6.5%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '6 days',
    CURRENT_TIMESTAMP - INTERVAL '5 days',
    CURRENT_TIMESTAMP - INTERVAL '6 days',
    CURRENT_TIMESTAMP - INTERVAL '5 days'
),
-- Deal 6: Inactive Approved Deal (for testing deactivate feature)
(
    gen_random_uuid(),
    'Palm Jumeirah Shoreline',
    'Palm Jumeirah',
    'dubai',
    'jumeirah',
    '3BR',
    '3',
    '1,680 sq ft',
    'AED 4,850,000',
    4850000,
    5850000,
    6050000,
    'AED 5,850,000 - 6,050,000',
    '17.5%',
    '5.4%',
    'READY',
    'APPROVED',
    false,
    CURRENT_TIMESTAMP - INTERVAL '7 days',
    CURRENT_TIMESTAMP - INTERVAL '6 days',
    CURRENT_TIMESTAMP - INTERVAL '7 days',
    CURRENT_TIMESTAMP - INTERVAL '6 days'
),
-- Deal 7: Active Approved Deal
(
    gen_random_uuid(),
    'Marina Walk Promenade',
    'Dubai Marina',
    'dubai',
    'marina',
    'Studio',
    'studio',
    '520 sq ft',
    'AED 785,000',
    785000,
    950000,
    985000,
    'AED 950,000 - 985,000',
    '18.6%',
    '7.5%',
    'OFF_PLAN',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '8 days',
    CURRENT_TIMESTAMP - INTERVAL '7 days',
    CURRENT_TIMESTAMP - INTERVAL '8 days',
    CURRENT_TIMESTAMP - INTERVAL '7 days'
),
-- Deal 8: Active Approved Deal
(
    gen_random_uuid(),
    'Emaar Boulevard Heights',
    'Downtown Dubai',
    'dubai',
    'downtown',
    '2BR',
    '2',
    '1,150 sq ft',
    'AED 3,150,000',
    3150000,
    3800000,
    3950000,
    'AED 3,800,000 - 3,950,000',
    '17.9%',
    '5.7%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '9 days',
    CURRENT_TIMESTAMP - INTERVAL '8 days',
    CURRENT_TIMESTAMP - INTERVAL '9 days',
    CURRENT_TIMESTAMP - INTERVAL '8 days'
),
-- Deal 9: Active Approved Deal
(
    gen_random_uuid(),
    'Business Bay Canal View',
    'Business Bay',
    'dubai',
    'business-bay',
    '1BR',
    '1',
    '680 sq ft',
    'AED 1,185,000',
    1185000,
    1425000,
    1480000,
    'AED 1,425,000 - 1,480,000',
    '17.6%',
    '6.9%',
    'OFF_PLAN',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '10 days',
    CURRENT_TIMESTAMP - INTERVAL '9 days',
    CURRENT_TIMESTAMP - INTERVAL '10 days',
    CURRENT_TIMESTAMP - INTERVAL '9 days'
),
-- Deal 10: Active Approved Deal
(
    gen_random_uuid(),
    'The Beach Residence',
    'JBR',
    'dubai',
    'jumeirah',
    '1BR',
    '1',
    '720 sq ft',
    'AED 1,650,000',
    1650000,
    1990000,
    2065000,
    'AED 1,990,000 - 2,065,000',
    '18.1%',
    '6.3%',
    'READY',
    'APPROVED',
    true,
    CURRENT_TIMESTAMP - INTERVAL '11 days',
    CURRENT_TIMESTAMP - INTERVAL '10 days',
    CURRENT_TIMESTAMP - INTERVAL '11 days',
    CURRENT_TIMESTAMP - INTERVAL '10 days'
)
ON CONFLICT DO NOTHING;

-- Verify the inserts
SELECT
    COUNT(*) as total_approved,
    COUNT(*) FILTER (WHERE active = true) as active_deals,
    COUNT(*) FILTER (WHERE active = false) as inactive_deals
FROM deals
WHERE status = 'APPROVED';

-- Show sample of inserted deals
SELECT
    name,
    location,
    city,
    bedrooms,
    listed_price,
    discount,
    status,
    active,
    approved_at
FROM deals
WHERE status = 'APPROVED'
ORDER BY approved_at DESC
LIMIT 10;

